version: '3.1'

services: 
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    deploy:
      replicas: 5
 
  httpd:
    image: httpd:latest
    ports:
      - 8081:80
    deploy:
      replicas: 5

  logspout:
    image: bekt/logspout-logstash:latest
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ROUTE_URIS=logstash://172.31.124.128:5000
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M

